# rust/openai_tts_handler/Makefile.toml

[tasks.build]
command = "cross"
args = ["build", "--release", "--target", "x86_64-unknown-linux-musl"]

[tasks.zip]
command = "powershell"
args = ["Compress-Archive", "-Path", ".\\target\\x86_64-unknown-linux-musl\\release\\bootstrap", "-DestinationPath", "openai_tts_handler.zip", "-Force"]

[tasks.default]
dependencies = ["build", "zip"]
